---
title: "WhoGov_script"
author: "Domenic Hög"
date: "2024-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading data set

```{r}
WhoGov_within <- read.csv("WhoGov_within_V2.0.csv")
```

# Data wrangling
## Splitting names 
```{r}
WhoGov_within <- WhoGov_within %>%
  separate(name, into = c("First Name", "Last Name"), sep = " (?=[^ ]+$)", remove = FALSE)
```

## Deleting special characters
```{r}
library(stringr)

replace_special_chars <- function(x) {
  str_replace_all(x, c(
    "\\(" = " ",   
    "\\)" = " ",   
    "&" = "and",   
    "_" = " ",     
    "," = " ",     
    "'" = ""      
  ))
}

WhoGov_within <- WhoGov_within %>%
  mutate_all(~ replace_special_chars(.))

# Forgotthe hyphens
replace_hyphens <- function(x) {
  str_replace_all(x, "-", " ")
}

WhoGov_within <- WhoGov_within %>%
  mutate_all(~ replace_hyphens(.))

# Replacing the Min. by Minister
replace_min<- function(x) {
  str_replace_all(x, "Min\\.", "Minister")
}

WhoGov_within <- WhoGov_within %>%
  mutate_all(~ replace_min(.))

```

